version: '3.8'

# IA Continu Solution - Working Configuration
# Fixed all service issues and networking problems

services:
  # FastAPI ML Application Service
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: ia_continu_api
    ports:
      - "8000:8000"
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ia_continu_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MLflow Tracking Service
  mlflow:
    build:
      context: .
      dockerfile: services/mlflow/Dockerfile
    container_name: ia_continu_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/app/mlflow
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///app/mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/app/mlruns
    restart: unless-stopped
    networks:
      - ia_continu_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Prefect Server (Orchestration)
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    container_name: ia_continu_prefect_server
    ports:
      - "4200:4200"
    volumes:
      - ./prefect_data:/root/.prefect
      - ./logs:/app/logs
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
    restart: unless-stopped
    networks:
      - ia_continu_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:4200/api/ready', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Prefect ML Automation Worker
  prefect-automation:
    build:
      context: .
      dockerfile: services/prefect/Dockerfile
    container_name: ia_continu_prefect_automation
    depends_on:
      - prefect-server
      - api
      - mlflow
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - API_URL=http://api:8000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - PYTHONIOENCODING=utf-8
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ia_continu_network

  # Streamlit UI Service
  streamlit:
    build:
      context: .
      dockerfile: services/streamlit/Dockerfile
    container_name: ia_continu_streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - ia_continu_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Uptime Kuma (Simple Monitoring)
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: ia_continu_uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - ./uptime_kuma_data:/app/data
    restart: unless-stopped
    networks:
      - ia_continu_network

# Network Configuration
networks:
  ia_continu_network:
    driver: bridge
    name: ia_continu_network
