version: '3.8'

services:
  # FastAPI ML Application
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    volumes:
      - app_data:/app/data
      - app_models:/app/models
      - app_logs:/app/logs
    depends_on:
      - prefect-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    container_name: prefect-server
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
      - app_logs:/app/logs
    restart: unless-stopped
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_UI_API_URL=http://localhost:4200/api
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:4200/health', timeout=5)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  # MLflow Server
  mlflow-server:
    image: python:3.11-slim
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/tmp/mlflow
    command: >
      bash -c "
        pip install mlflow==2.8.1 requests &&
        mkdir -p /tmp/mlflow /tmp/mlruns &&
        mlflow server
        --backend-store-uri sqlite:///tmp/mlflow/mlflow.db
        --default-artifact-root /tmp/mlruns
        --host 0.0.0.0
        --port 5000
        --serve-artifacts
        --gunicorn-opts '--bind 0.0.0.0:5000'
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    container_name: prefect-worker
    depends_on:
      prefect-server:
        condition: service_healthy
      app:
        condition: service_healthy
      mlflow-server:
        condition: service_healthy
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PYTHONIOENCODING=utf-8
      - API_URL=http://fastapi_app:8000
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    volumes:
      - app_logs:/app/logs
      - app_models:/app/models
      - app_data:/app/data
    restart: unless-stopped

  # Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

volumes:
  app_data:
  app_models:
  app_logs:
  prefect_data:
  uptime-kuma-data:
  mlflow_data: