global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI ML Service
  - job_name: 'ia-continu-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # MLflow Service
  - job_name: 'ia-continu-mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/'
    scrape_interval: 30s

  # Prefect Service
  - job_name: 'ia-continu-prefect'
    static_configs:
      - targets: ['prefect-server:4200']
    metrics_path: '/api/ready'
    scrape_interval: 30s

  # Streamlit Service
  - job_name: 'ia-continu-streamlit'
    static_configs:
      - targets: ['streamlit:8501']
    metrics_path: '/_stcore/health'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
