global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the FastAPI application metrics
  - job_name: 'ia-continu-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape MLflow metrics if available
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Scrape Prefect server metrics
  - job_name: 'prefect-server'
    static_configs:
      - targets: ['prefect_server:4200']
    metrics_path: '/api/ready'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Scrape Streamlit metrics if available
  - job_name: 'streamlit'
    static_configs:
      - targets: ['streamlit:8501']
    metrics_path: '/_stcore/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom ML metrics endpoint
  - job_name: 'ml-monitoring'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/ml-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
